name: gpa_calcos
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  flutter_gemini: ^2.0.3
  carousel_slider: ^4.0.0

  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  auto_route: ^7.9.2
  google_mlkit_image_labeling: ^0.10.0
  image_picker: ^1.0.8
  dash_chat_2: ^0.0.20
  screenshot: ^3.0.0
  share_plus: ^9.0.0
dev_dependencies: 
  auto_route_generator: ^7.3.2
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter_icons:  # Correct typos and indentation
    image_path: "try.png"  # Replace with the actual path to your icon
    android: true    
flutter:
  uses-material-design: true
  assets:
    - assets/


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
